### ISSUE TITLE
Thanks for forking!!!

### ISSUE THREAD

**Issue by phpfui** [druidfi/mysqldump-php#11]
Great to see someone take over this project.  I was thinking of doing this myself, but you beat me to it.

I would consider merging in the PR's from the original project where they make sense.

I can help you out with anything you thing would add to the project.  Let me know where I can help.

And thanks for the fork!

**Comment by back-2-95** [comment]
No problem @phpfui 

The help is always appreciated. I'm not having currently any "roadmap" for this. Forking and creating a new package was more like providing supported path to future as we (Druid as company) rely on this package quite much.

**Comment by back-2-95** [comment]
If you have ideas, I guess now they could be added as issues here. I also tried to go through some old PRs in the original repo if there is something to salvage.

**Comment by phpfui** [comment]
I think adding SQL before and after the backup would be helpful.  I see there is a PR in the old project for that.  I would like that as well, so I will look into porting that.

Another option would be to name the file that is product and then compressed.  Both the file in the zip and the compressed could be named.  I would like this as well, maybe it is already possible.

It might be worth going through the outstanding PR's on the original project and inviting them to submit a PR on this project if they still have an issue (not sure what you fixed, but seems to be a lot).

Let me know if you like any of these ideas and I can do them (including commenting on old PR's).

**Comment by back-2-95** [comment]
I think those ideas will come more real with PRs. I'd also like to see some background and/or use cases in the PR descriptions to open up why.

I also commented on some old PRs if I included them here.I think they were mostly about PHP 8.x stuff.

**Comment by phpfui** [comment]
Let's get the Actions working, then I will submit a PR for naming the files.

**Comment by back-2-95** [comment]
Ok, let's continue in specific issues and PRs. Again, great to have more 💪
