### ISSUE TITLE
Virtual columns cause side effects (complete inserts switched on) and break gdpr-dump of Shopware 6

### ISSUE THREAD

**Issue by amenk** [druidfi/mysqldump-php#17]
When virtual columns appear during dumping, complete-inserts are switched on.

With generated columns it causes also a "Column count doesn't match value count"

See here for more details: https://github.com/Smile-SA/gdpr-dump/issues/78

**Comment by amenk** [comment]
I believe the culprit is this line:

https://github.com/ifsnop/mysqldump-php/blob/b232c2b6b2e250d716f936b0d11eda6bc2ec3df4/src/Ifsnop/Mysqldump/Mysqldump.php#L1274

**Comment by back-2-95** [comment]
Maybe that setting value to true could be changed with some method e.g. `disableCompleteInsert()`.

Could you provide a PR?

**Comment by amenk** [comment]
The real problem is, that dumping tables with generated columns is breaking when complete inserts are on; so we will probably need to try to fix this one first. The side effect is just strange, but might be neglectable - I am wondering why they are being switched on when there are virtual columns.

**Comment by amenk** [comment]
will try to make a PR

**Comment by amenk** [comment]
There is already [test ](https://github.com/druidfi/mysqldump-php/blob/main/tests/scripts/test011.src.sql) for GENERATED / VIRTUAL columns, which works. still need to make a minimal reproducible sample. Maybe it's related to the hex-blob option which is currently not set in the test. But simply setting it to true also does not make the test fail, maybe binary columns are needed....

**Comment by amenk** [comment]
Thank you
