### ISSUE TITLE
The hook provided by `setInfoHook` is called too late

### ISSUE THREAD

**Issue by guvra** [druidfi/mysqldump-php#39]
Hi,

I'm working on a feature for gdpr-dump that displays the dump progress with a progress bar:
https://github.com/Smile-SA/gdpr-dump/pull/113

The goal is to be able to know which tables take a long time to dump when creating a dump file for a very big database.

I'm using the function `setInfoHook` to make the progress bar advance.
However, it's not working properly, because the hook is triggered **after** a table was dumped.
Instead of displaying the name of the table that is being dumped, it displays the name of the previous table.

For this feature to work properly, I either need the hook to be moved before a table is dumped, or another hook to be added.
What do you think would be the best solution?
I can provide a PR.

**Comment by staabm** [comment]
in case we implent the suggestion in https://github.com/druidfi/mysqldump-php/pull/38/files#r1505546205 the current event could stay after the dump and it should work without a BC break

**Comment by back-2-95** [comment]
@guvra you good with this one now that 1.1.0 was released?

**Comment by guvra** [comment]
@back-2-95 Yes, it's working fine, thanks for the new release :+1:
